spring.datasource.url=jdbc:mysql://localhost:51168/meinedb
spring.datasource.username=user
spring.datasource.password=userpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver